# Generated by Django 5.1 on 2024-09-28 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_alter_appointment_doctor_and_more'),
        ('NSW', '0002_alter_patient_contact_number_alter_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='NSW.patient'),
        ),
    ]
