# Generated by Django 5.1 on 2024-09-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_alter_doctor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(choices=[('doctor1@gmail.com', 'doctor1@gmail.com'), ('doctor2@gmail.com', 'doctor2@gmail.com'), ('doctor3@gmail.com', 'doctor3@gmail.com')], default='doctor1@gmail.com', max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='Unnamed Doctor', max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(choices=[('+1234567890', '+1234567890'), ('+0987654321', '+0987654321'), ('+1122334455', '+1122334455')], default='+1234567890', max_length=15),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('general', 'General Practitioner'), ('cardiologist', 'Cardiologist'), ('pediatrician', 'Pediatrician'), ('dermatologist', 'Dermatologist')], default='general', max_length=255),
        ),
    ]
