# Generated by Django 5.1 on 2024-09-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0003_remove_doctor_specialization_remove_doctor_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
