# Generated by Django 5.1 on 2024-09-28 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_alter_doctor_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
    ]
